cmake -S . -B "build-dir" -G "Visual Studio 16 2019" -A x64 ^
    -DWITH_AVISYNTH=OFF -DWITH_CSRI=ON -DWITH_DIRECTSOUND=ON ^
    -DWITH_FFMS2=ON -DWITH_FFTW3=ON -DWITH_HUNSPELL=ON -DWITH_UCHARDET=ON ^
    -DWITH_XAUDIO2=ON -DWITH_BUILD_CREDIT=ON -DWITH_STARTUPLOG=OFF ^
    -DBUILD_CREDIT="\"Daydream Cafe Edition [Shinon]\"" ^
    -DBOOST_ROOT="C:\Boost" ^
    -DCMAKE_TOOLCHAIN_FILE="%cd%/vendor/extern/scripts/buildsystems/vcpkg.cmake" ^
    -DFFMS2_INCLUDE_DIRS="%cd%/vendor/extra/ffms/include" ^
    -DFFMS2_LIBRARIES="%cd%/vendor/extra/ffms/x64/ffms2.lib" ^
    -DwxWidgets_ROOT_DIR="%cd%/vendor/extern/installed/x64-windows-static" ^
    -DICU_ROOT="%cd%/vendor/extern/installed/x64-windows-static" ^
    -DHUNSPELL_LIBRARIES="%cd%/vendor/extern/installed/x64-windows-static/lib/libhunspell.lib" ^
    -DHUNSPELL_INCLUDE_DIR="%cd%/vendor/extern/installed/x64-windows-static/include" ^
    -DFFTW_INCLUDES="%cd%/vendor/extern/installed/x64-windows-static/include" ^
    -DFFTW_LIB="%cd%/vendor/extern/installed/x64-windows-static/lib/fftw3.lib" ^
    -DFFTWF_LIB="%cd%/vendor/extern/installed/x64-windows-static/lib/fftw3f.lib" ^
    -DFFTWL_LIB="%cd%/vendor/extern/installed/x64-windows-static/lib/fftw3l.lib" ^
    -Dass_INCLUDE_DIRS="%cd%/vendor/extra/libass/libass" ^
    -Dass_LIBRARIES="%cd%/vendor/extra/libass/bin/Release_x64/libass.lib" ^
    -Dunofficial-iconv_DIR="%cd%/vendor/extern/installed/x64-windows-static/share/unofficial-iconv" ^
    -DZLIB_INCLUDE_DIR="%cd%/vendor/extern/installed/x64-windows-static/include" ^
    -Duchardet_INCLUDE_DIRS="%cd%/vendor/extern/installed/x64-windows-static/include/uchardet" ^
    -Duchardet_LIBRARIES="%cd%/vendor/extern/installed/x64-windows-static/lib/libcharset.lib"
pause